UPDATE public.note SET animal_id = 455, note_text = 'in excellent health!', date_time = '2016-09-03' WHERE note_id = 10;
UPDATE public.note SET animal_id = 702, note_text = 'healthy', date_time = '2016-09-03' WHERE note_id = 11;
UPDATE public.note SET animal_id = 702, note_text = 'perfectly healthy', date_time = '2016-09-03' WHERE note_id = 12;
UPDATE public.note SET animal_id = 321, note_text = 'healthy. No checkup required', date_time = '2016-09-03' WHERE note_id = 13;
UPDATE public.note SET animal_id = 895, note_text = 'in perfect health', date_time = '2016-09-03' WHERE note_id = 14;
UPDATE public.note SET animal_id = 321, note_text = 'Latest checkup reveals that she is in great health!', date_time = '2016-09-06' WHERE note_id = 17;
UPDATE public.note SET animal_id = 6, note_text = 'A quick note to test....', date_time = '2016-09-08' WHERE note_id = 18;
UPDATE public.note SET animal_id = 5, note_text = 'Here is a test note', date_time = '2016-09-18' WHERE note_id = 19;
UPDATE public.note SET animal_id = 744, note_text = 'Great checkup today. Kitty-Kat tried to eat several cotton swabs, but other than that, super visit', date_time = '2016-09-19' WHERE note_id = 20;
UPDATE public.note SET animal_id = 12, note_text = 'Chelsea is in great health!', date_time = '2016-09-20' WHERE note_id = 23;
UPDATE public.note SET animal_id = 19, note_text = 'Mary needs to be eating more worms', date_time = '2016-09-20' WHERE note_id = 24;
UPDATE public.note SET animal_id = 21, note_text = 'Zilly is a healthy, happy cat', date_time = '2016-09-20' WHERE note_id = 25;
UPDATE public.note SET animal_id = 21, note_text = 'Zilly should not eating so much fish', date_time = '2016-09-20' WHERE note_id = 26;
UPDATE public.note SET animal_id = 25, note_text = 'Her symptons are acute. I think we should keep Laura overnight for observation', date_time = '2016-09-21' WHERE note_id = 27;
UPDATE public.note SET animal_id = 25, note_text = 'Laura seems to be afraid of the dark. I recommend her getting a nightlight.', date_time = '2016-09-21' WHERE note_id = 28;
UPDATE public.note SET animal_id = 107, note_text = 'This is the first note of the rest of PB&J''s life', date_time = '2016-11-19' WHERE note_id = 29;